version: '3'
services:
  fastapi_app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - fastapi_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/etc/nginx/html/
    networks:
      - fastapi_network
    depends_on:
      - fastapi_app 
networks:
  fastapi_network:
    driver: bridge
   
 