version: '3'
services:
  fastapi_app:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - fastapi_network
    depends_on:
      - mongodb
    restart: on-failure
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/etc/nginx/html/
    networks:
      - fastapi_network
    depends_on:
      - fastapi_app 

  mongodb:
    container_name: mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - fastapi_network
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    
  mongo_express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - fastapi_network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_SITE_BASEURL: /admin/
    depends_on:
      - mongodb
     
    
networks:
  fastapi_network:
    driver: bridge
volumes:
  mongo_data:
   
 