name: Build and Deploy Docker

# Déclencheur : Lorsque des changements sont poussés sur la branche main
on:
  push:
    branches:
      - action_git

jobs:
  build:
    # Utilisation d'un runner self-hosted au lieu d'ubuntu-latest
    runs-on: self-hosted

    steps:
      # Étape 1 : Checkout du code source du dépôt
      - name: Checkout repository
        uses: actions/checkout@v2

      # Étape 2 : Configurer Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Supprimer les conteneurs Docker en cours d'exécution
      - name: Remove existing Docker containers
        run: |
          docker-compose -f docker-compose.yml down

      # Étape 4 : Construire les images Docker
      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yml build

      # Étape 5 : Relancer les conteneurs Docker
      - name: Run Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d
