name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4

    # Build the Docker image for fastapi_app
    - name: Build the Docker image
      run: docker compose -f docker-compose.yaml build fastapi_app

    # Log in to Docker Hub using secrets
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    # Tag the built image with your Docker Hub repository name
    - name: Tag the Docker image
      run: docker tag projet_devops-fastapi_app:latest jacques4879/cicd_test:latest

    # Push the image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: docker push jacques4879/cicd_test:latest

    # Error Handling (optional)
    - name: Error Handling
      if: failure()
      run: "echo erreur"
